/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DealerMotor;

/**
 *
 * @author THE MAGIC
 */
public class DealerMotor extends javax.swing.JFrame {
    boolean lanjut = false;
    
//    arrays
    String[][] hargaYamaha = {{"Rp66.000.000", "Rp31.615.000", "Rp27.425.000"},
                              {"Rp25.870.000", "Rp19.790.000", "Rp17.915.000"},
                              {"Rp39.875.000", "Rp63.450.000", "Rp37.775.900"}};
    String[][] hargaHonda = {{"Rp32.620.000", "Rp26.539.000", "Rp22.500.000"},
                           {"Rp19.100.000", "Rp16.020.000", "Rp25.280.000"},
                           {"Rp37.283.000", "Rp75.656.000", "Rp33.710.000"}};
    String[][] hargaSuzuki = {{"Rp29.970.000", "Rp18.640.000", "Rp18.340.000"},
                           {"Rp34.230.000", "Rp30.510.000", "Rp51.090.000"}};
    String[][] hargaKawasaki = {{"Rp66.900.000", "Rp105.000.000", "Rp129.900.000"}};
    
    /**
     * Creates new form DealerMotor
     */
    public DealerMotor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brandMotor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jenisMotor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        produkMotor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        hargaMotor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("epyMotors");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Brand");

        brandMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yamaha", "Honda", "Suzuki", "Kawasaki" }));
        brandMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandMotorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Jenis Motor");

        jenisMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matic", "Manual", "Sport" }));
        jenisMotor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jenisMotorItemStateChanged(evt);
            }
        });
        jenisMotor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jenisMotorFocusLost(evt);
            }
        });
        jenisMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisMotorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Produk");

        produkMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yamaha XMAX 250", "Yamaha NMAX 155", "Yamaha Aerox 155" }));
        produkMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkMotorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Harga");

        hargaMotor.setEnabled(false);
        hargaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaMotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(produkMotor, javax.swing.GroupLayout.Alignment.LEADING, 0, 192, Short.MAX_VALUE)
                            .addComponent(jenisMotor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brandMotor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hargaMotor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brandMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jenisMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(produkMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brandMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandMotorActionPerformed
        String[] listYamaha = {"Matic", 
                               "Manual", 
                               "Sport"};
        
        String[] listHonda = {"Matic",
                              "Manual",
                              "Sport"};
        
        String[] listSuzuki = {"Matic", "Sport"};
        
        String[] listKawasaki = {"Sport"};
        
        int brandMotorInd = brandMotor.getSelectedIndex();
        String[] chosen;
        
        if(brandMotorInd == 0){
            chosen = listYamaha;
        }else if(brandMotorInd == 1){
            chosen = listHonda;
        }else if(brandMotorInd == 2){
            chosen = listSuzuki;
        }else if(brandMotorInd == 3){
            chosen = listKawasaki;
        }else {
            chosen = listYamaha;
        }
        
        jenisMotor.setEnabled(true);
        jenisMotor.removeAllItems();
        for(String item : chosen){
            jenisMotor.addItem(item);
        }
        
    }//GEN-LAST:event_brandMotorActionPerformed

    private void jenisMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisMotorActionPerformed
        
        
    }//GEN-LAST:event_jenisMotorActionPerformed

    private void produkMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkMotorActionPerformed
        hargaMotor.setText( Integer.toString(brandMotor.getSelectedIndex()) + " " + Integer.toString(jenisMotor.getSelectedIndex()));
        Object brandMotorInd = brandMotor.getSelectedItem();
        Object jenisMotorInd = jenisMotor.getSelectedItem();
        
        String[] chosen;
        if(brandMotorInd == "Yamaha"){
            if(jenisMotorInd == "Matic"){
                chosen = this.hargaYamaha[0];
                
            }else if(jenisMotorInd == "Manual"){
                chosen = this.hargaYamaha[1];
                
            } else {
                chosen = this.hargaYamaha[2];

            }
        }else if(brandMotorInd == "Honda"){
            if(jenisMotorInd == "Matic"){
                chosen = this.hargaHonda[0];
            }else if(jenisMotorInd == "Manual"){
                chosen = this.hargaHonda[1];
            } else {
                chosen = this.hargaHonda[2];
            }
        }else if(brandMotorInd == "Suzuki"){
            if(jenisMotorInd == "Matic"){
                chosen = this.hargaSuzuki[0];
            }else {
                chosen = this.hargaSuzuki[1];}
        }else{
            chosen = this.hargaKawasaki[0];
        }
        for (int i = 0; i < 3; i++) {
                if(produkMotor.getSelectedIndex() == i){
                    hargaMotor.setText(chosen[i]);
                }
            }
            hargaMotor.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_produkMotorActionPerformed

    private void jenisMotorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jenisMotorItemStateChanged
        // TODO add your handling code here:
        if(this.lanjut == false){
            this.lanjut = true;
            return;
        }
        String[][] listYamaha = {{"XMAX 250", "NMAX 155", "Aerox 155"},
                                 {"MX King 150", "Jupiter Z1", "Vega Force"},
                                 {"R15", "R25", "XSR 155"}};
        
        String[][] listHonda = {{"PCX", "Vario 160", "Vario 125"},
                                {"Supra X 125", "Revo", "Supra GTR 150"},
                                {"CBR150R", "CBR250RR", "CB150X"}};
        
        String[][] listSuzuki = {{"Avenis 125", "Nex II", "Address FI"},
                                 {"GSX-R150","GSX-S150", "Gixxer SF 250"}};
        
        String[][] listKawasaki = {{"Ninja 250", "Ninja ZX-25RR", "Ninja ZX-25R"}};
        
        int brandMotorInd = brandMotor.getSelectedIndex();
        int jenisMotorInd = jenisMotor.getSelectedIndex();
        String naming = "Yamaha";
        String[][] chosen;
        
        if(brandMotorInd == 0){
            chosen = listYamaha;
            naming = "Yamaha ";
        }else if(brandMotorInd == 1){
            chosen = listHonda;
                        naming = "Honda ";

        }else if(brandMotorInd == 2){
            chosen = listSuzuki;
                        naming = "Suzuki ";

        }else if(brandMotorInd == 3){
            chosen = listKawasaki;
                        naming = "Kawasaki ";

        }else {
            chosen = null;
        }
        produkMotor.removeAllItems();
        for (String item : chosen[jenisMotorInd]){
            produkMotor.addItem(naming + item);
        }
this.lanjut = false;
    }//GEN-LAST:event_jenisMotorItemStateChanged

    private void jenisMotorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisMotorFocusLost
        // TODO add your handling code here:
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jenisMotorFocusLost

    private void hargaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealerMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealerMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealerMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealerMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealerMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandMotor;
    private javax.swing.JTextField hargaMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jenisMotor;
    private javax.swing.JComboBox<String> produkMotor;
    // End of variables declaration//GEN-END:variables
}
