/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cucimotor;

/**
 *
 * @author BagasAp
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        merekMotor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenisMotor = new javax.swing.JComboBox<>();
        namaMotor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("epyMotors");

        merekMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Yamaha", "Suzuki" }));
        merekMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputChangesPerformedCustom(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel3.setText("Merek Motor");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel2.setText("Jenis Motor");

        jenisMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matic", "Manual", "Sport" }));
        jenisMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputChangesPerformedCustom(evt);
            }
        });

        namaMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Merek" }));
        namaMotor.setEnabled(false);
        namaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMotorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel4.setText("Nama Motor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(merekMotor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jenisMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(namaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jenisMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(merekMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMotorActionPerformed

    private void inputChangesPerformedCustom(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputChangesPerformedCustom
        String hondaMotors[] = {"Honda Beat",
                                "Honda Vario", 
                                "Honda PCX"};// TODO add your handling code here:
        
        String hondaManualMotors[] = {"Honda Manual",
                                "Honda Manual", 
                                "Honda Manual"};
        
        String yamahaMotors[] = {"Yamaha Aerox",
                                "Yamaha Fazzio", 
                                "Yamaha Nmax"};// TODO add your handling code here:
        
        String yamahaManualMotors[] = {"Yamaha Manual",
                                "Yamaha Manual", 
                                "Yamaha Manual"};
        
        String suzukiMotors[] = {"Suzuki Address",
                                "Suzuki Nex", 
                                "Suzuki Avenis"};// TODO add your handling code here:
        
        String suzukiManualMotors[] = {"Suzuki Manual",
                                "Suzuki Nex", 
                                "Suzuki Avenis"};
        
        String kawasakiMotors[] = {"Kawasaki H2",
                                   "Ninja ZX25R",
                                   "Ninja ZX636",
                                   "Ninja Z900"};
        
        String chosen[];
        int merekMotorInd = merekMotor.getSelectedIndex();
        int jenisMotorInd = jenisMotor.getSelectedIndex();
        
        if(merekMotorInd == 0){
            if(jenisMotorInd == 0){
                chosen = hondaMotors;
                
            } else {
                chosen = hondaManualMotors;
            }
        } else if(merekMotorInd == 1){
            if(jenisMotorInd == 0){
                chosen = yamahaMotors;
                
            } else {
                chosen = yamahaManualMotors;
            }
        } else if(merekMotorInd == 2){
            if(jenisMotorInd == 0){
                chosen = suzukiMotors;
                
            } else {
                chosen = suzukiManualMotors;
            }
        } else {
            if(jenisMotorInd == 2){
                chosen = kawasakiMotors;
            }
            chosen = null;
        }
        namaMotor.removeAllItems();
        namaMotor.setEnabled(true);
        for (String item : chosen){
            namaMotor.addItem(item);
        }// TODO add your handling code here:
    }//GEN-LAST:event_inputChangesPerformedCustom

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jenisMotor;
    private javax.swing.JComboBox<String> merekMotor;
    private javax.swing.JComboBox<String> namaMotor;
    // End of variables declaration//GEN-END:variables
}
